- apt_repository: repo=ppa:nginx/stable
- apt: pkg=nginx
- service: name=nginx enabled=yes state=started
- name: upload nginx config
  synchronize: src=nginx dest=/etc dirs=yes delete=yes checksum=yes times=no rsync_path="sudo rsync"
- template: src=rails_app.conf dest=/etc/nginx/vhosts.d/{{ app_name }}.conf
  notify: restart nginx
