---
- name: add {{ user }} to www-data
  user: name={{ user }} append=yes groups=www-data

- name: apt-get update
  apt: update_cache=yes cache_valid_time=86400
- name: install common packages
  apt: name={{ item }}
  with_items:
    - fail2ban
    - git-core
    - vim
    - screen
    - moreutils
    - autoconf
    - make
    - cmake
    - gcc
    - curl
    - libxml2-dev
    - libxslt-dev
    - libcurl4-openssl-dev
    - g++
    - mosh
    - libmariadbclient-dev
    - htop

- service: name=fail2ban enabled=yes state=started

- name: create folders for mina
  file: path=/home/{{ user }}/{{ item }} state=directory owner={{ user }} group=www-data mode=700
  with_items:
    - shared
    - bundle
    - config
    - releases
    - log
    - tmp
    - tmp/cache
    - tmp/pids
    - tmp/sessions
    - tmp/sockets

- name: Add SSH key from Github
  authorized_key: user={{ user }} key=https://github.com/{{ github_user }}.keys

- name: add known ssh hosts
  shell: ssh-keyscan -H bitbucket.org github.com > /home/{{ user }}/.ssh/known_hosts
  args:
    creates: /home/{{ user }}/.ssh/known_hosts

- name: fix ownership for known hosts
  file: path=/home/{{ user }}/.ssh/known_hosts mode=0600 owner={{ user }}

- name: fix ownership for authorized_keys
  file: path=/home/{{ user }}/.ssh/authorized_keys mode=0600 owner={{ user }}
